#ifndef HARDWARE_DP32G030_RTC_H
#define HARDWARE_DP32G030_RTC_H

#if !defined(__ASSEMBLY__)
#include <stdint.h>
#endif

/* -------- RTC -------- */
#define RTC_BASE_ADDR									0x40069000U
#define RTC_BASE_SIZE									0x00000030U

#define RTC_RTC_CFG_ADDR								(RTC_BASE_ADDR + 0x0000U)
#define RTC_RTC_CFG     								(*(volatile uint32_t *)RTC_RTC_CFG_ADDR)

#define RTC_RTC_CFG_RTC_EN_SHIFT        				0
#define RTC_RTC_CFG_RTC_EN_WIDTH        				1
#define RTC_RTC_CFG_RTC_EN_MASK         				(((1U << RTC_RTC_CFG_RTC_EN_WIDTH) - 1U) << RTC_RTC_CFG_RTC_EN_SHIFT)
#define RTC_RTC_CFG_RTC_EN_VALUE_DISABLE				0U
#define RTC_RTC_CFG_RTC_EN_BITS_DISABLE 				(RTC_RTC_CFG_RTC_EN_VALUE_DISABLE << RTC_RTC_CFG_RTC_EN_SHIFT)
#define RTC_RTC_CFG_RTC_EN_VALUE_ENABLE 				1U
#define RTC_RTC_CFG_RTC_EN_BITS_ENABLE  				(RTC_RTC_CFG_RTC_EN_VALUE_ENABLE << RTC_RTC_CFG_RTC_EN_SHIFT)

#define RTC_RTC_CFG_ALM_EN_SHIFT        				1
#define RTC_RTC_CFG_ALM_EN_WIDTH        				1
#define RTC_RTC_CFG_ALM_EN_MASK         				(((1U << RTC_RTC_CFG_ALM_EN_WIDTH) - 1U) << RTC_RTC_CFG_ALM_EN_SHIFT)
#define RTC_RTC_CFG_ALM_EN_VALUE_DISABLE				0U
#define RTC_RTC_CFG_ALM_EN_BITS_DISABLE 				(RTC_RTC_CFG_ALM_EN_VALUE_DISABLE << RTC_RTC_CFG_ALM_EN_SHIFT)
#define RTC_RTC_CFG_ALM_EN_VALUE_ENABLE 				1U
#define RTC_RTC_CFG_ALM_EN_BITS_ENABLE  				(RTC_RTC_CFG_ALM_EN_VALUE_ENABLE << RTC_RTC_CFG_ALM_EN_SHIFT)

#define RTC_RTC_CFG_LOAD_EN_SHIFT        				2
#define RTC_RTC_CFG_LOAD_EN_WIDTH        				1
#define RTC_RTC_CFG_LOAD_EN_MASK         				(((1U << RTC_RTC_CFG_LOAD_EN_WIDTH) - 1U) << RTC_RTC_CFG_LOAD_EN_SHIFT)
#define RTC_RTC_CFG_LOAD_EN_VALUE_DISABLE				0U
#define RTC_RTC_CFG_LOAD_EN_BITS_DISABLE 				(RTC_RTC_CFG_LOAD_EN_VALUE_DISABLE << RTC_RTC_CFG_LOAD_EN_SHIFT)
#define RTC_RTC_CFG_LOAD_EN_VALUE_ENABLE 				1U
#define RTC_RTC_CFG_LOAD_EN_BITS_ENABLE  				(RTC_RTC_CFG_LOAD_EN_VALUE_ENABLE << RTC_RTC_CFG_LOAD_EN_SHIFT)


#define RTC_RTC_IE_ADDR									(RTC_BASE_ADDR + 0x0004U)
#define RTC_RTC_IE     									(*(volatile uint32_t *)RTC_RTC_IE_ADDR)

#define RTC_RTC_IE_SEC_IE_SHIFT        				0
#define RTC_RTC_IE_SEC_IE_WIDTH        				1
#define RTC_RTC_IE_SEC_IE_MASK         				(((1U << RTC_RTC_IE_SEC_IE_WIDTH) - 1U) << RTC_RTC_IE_SEC_IE_SHIFT)
#define RTC_RTC_IE_SEC_IE_VALUE_DISABLE				0U
#define RTC_RTC_IE_SEC_IE_BITS_DISABLE 				(RTC_RTC_IE_SEC_IE_VALUE_DISABLE << RTC_RTC_IE_SEC_IE_SHIFT)
#define RTC_RTC_IE_SEC_IE_VALUE_ENABLE 				1U
#define RTC_RTC_IE_SEC_IE_BITS_ENABLE  				(RTC_RTC_IE_SEC_IE_VALUE_ENABLE << RTC_RTC_IE_SEC_IE_SHIFT)

#define RTC_RTC_IE_MIN_IE_SHIFT        				1
#define RTC_RTC_IE_MIN_IE_WIDTH        				1
#define RTC_RTC_IE_MIN_IE_MASK         				(((1U << RTC_RTC_IE_MIN_IE_WIDTH) - 1U) << RTC_RTC_IE_MIN_IE_SHIFT)
#define RTC_RTC_IE_MIN_IE_VALUE_DISABLE				0U
#define RTC_RTC_IE_MIN_IE_BITS_DISABLE 				(RTC_RTC_IE_MIN_IE_VALUE_DISABLE << RTC_RTC_IE_MIN_IE_SHIFT)
#define RTC_RTC_IE_MIN_IE_VALUE_ENABLE 				1U
#define RTC_RTC_IE_MIN_IE_BITS_ENABLE  				(RTC_RTC_IE_MIN_IE_VALUE_ENABLE << RTC_RTC_IE_MIN_IE_SHIFT)

#define RTC_RTC_IE_HOUR_IE_SHIFT        				2
#define RTC_RTC_IE_HOUR_IE_WIDTH        				1
#define RTC_RTC_IE_HOUR_IE_MASK         				(((1U << RTC_RTC_IE_HOUR_IE_WIDTH) - 1U) << RTC_RTC_IE_HOUR_IE_SHIFT)
#define RTC_RTC_IE_HOUR_IE_VALUE_DISABLE				0U
#define RTC_RTC_IE_HOUR_IE_BITS_DISABLE 				(RTC_RTC_IE_HOUR_IE_VALUE_DISABLE << RTC_RTC_IE_HOUR_IE_SHIFT)
#define RTC_RTC_IE_HOUR_IE_VALUE_ENABLE 				1U
#define RTC_RTC_IE_HOUR_IE_BITS_ENABLE  				(RTC_RTC_IE_HOUR_IE_VALUE_ENABLE << RTC_RTC_IE_HOUR_IE_SHIFT)

#define RTC_RTC_IE_DATE_IE_SHIFT        				3
#define RTC_RTC_IE_DATE_IE_WIDTH        				1
#define RTC_RTC_IE_DATE_IE_MASK         				(((1U << RTC_RTC_IE_DATE_IE_WIDTH) - 1U) << RTC_RTC_IE_DATE_IE_SHIFT)
#define RTC_RTC_IE_DATE_IE_VALUE_DISABLE				0U
#define RTC_RTC_IE_DATE_IE_BITS_DISABLE 				(RTC_RTC_IE_DATE_IE_VALUE_DISABLE << RTC_RTC_IE_DATE_IE_SHIFT)
#define RTC_RTC_IE_DATE_IE_VALUE_ENABLE 				1U
#define RTC_RTC_IE_DATE_IE_BITS_ENABLE  				(RTC_RTC_IE_DATE_IE_VALUE_ENABLE << RTC_RTC_IE_DATE_IE_SHIFT)

#define RTC_RTC_IE_ALM_IE_SHIFT        				4
#define RTC_RTC_IE_ALM_IE_WIDTH        				1
#define RTC_RTC_IE_ALM_IE_MASK         				(((1U << RTC_RTC_IE_ALM_IE_WIDTH) - 1U) << RTC_RTC_IE_ALM_IE_SHIFT)
#define RTC_RTC_IE_ALM_IE_VALUE_DISABLE				0U
#define RTC_RTC_IE_ALM_IE_BITS_DISABLE 				(RTC_RTC_IE_ALM_IE_VALUE_DISABLE << RTC_RTC_IE_ALM_IE_SHIFT)
#define RTC_RTC_IE_ALM_IE_VALUE_ENABLE 				1U
#define RTC_RTC_IE_ALM_IE_BITS_ENABLE  				(RTC_RTC_IE_ALM_IE_VALUE_ENABLE << RTC_RTC_IE_ALM_IE_SHIFT)

#define RTC_RTC_IE_MS_IE_SHIFT        				5
#define RTC_RTC_IE_MS_IE_WIDTH        				1
#define RTC_RTC_IE_MS_IE_MASK         				(((1U << RTC_RTC_IE_MS_IE_WIDTH) - 1U) << RTC_RTC_IE_MS_IE_SHIFT)
#define RTC_RTC_IE_MS_IE_VALUE_DISABLE				0U
#define RTC_RTC_IE_MS_IE_BITS_DISABLE 				(RTC_RTC_IE_MS_IE_VALUE_DISABLE << RTC_RTC_IE_MS_IE_SHIFT)
#define RTC_RTC_IE_MS_IE_VALUE_ENABLE 				1U
#define RTC_RTC_IE_MS_IE_BITS_ENABLE  				(RTC_RTC_IE_MS_IE_VALUE_ENABLE << RTC_RTC_IE_MS_IE_SHIFT)

#define RTC_RTC_IF_ADDR									(RTC_BASE_ADDR + 0x0008U)
#define RTC_RTC_IF     									(*(volatile uint32_t *)RTC_RTC_IF_ADDR)

#define RTC_RTC_IF_SEC_IF_SHIFT        				0
#define RTC_RTC_IF_SEC_IF_WIDTH        				1
#define RTC_RTC_IF_SEC_IF_MASK         				(((1U << RTC_RTC_IF_SEC_IF_WIDTH) - 1U) << RTC_RTC_IF_SEC_IF_SHIFT)
#define RTC_RTC_IF_SEC_IF_VALUE_DISABLE				0U
#define RTC_RTC_IF_SEC_IF_BITS_DISABLE 				(RTC_RTC_IF_SEC_IF_VALUE_DISABLE << RTC_RTC_IF_SEC_IF_SHIFT)
#define RTC_RTC_IF_SEC_IF_VALUE_ENABLE 				1U
#define RTC_RTC_IF_SEC_IF_BITS_ENABLE  				(RTC_RTC_IF_SEC_IF_VALUE_ENABLE << RTC_RTC_IF_SEC_IF_SHIFT)

#define RTC_RTC_IF_MIN_IF_SHIFT        				1
#define RTC_RTC_IF_MIN_IF_WIDTH        				1
#define RTC_RTC_IF_MIN_IF_MASK         				(((1U << RTC_RTC_IF_MIN_IF_WIDTH) - 1U) << RTC_RTC_IF_MIN_IF_SHIFT)
#define RTC_RTC_IF_MIN_IF_VALUE_DISABLE				0U
#define RTC_RTC_IF_MIN_IF_BITS_DISABLE 				(RTC_RTC_IF_MIN_IF_VALUE_DISABLE << RTC_RTC_IF_MIN_IF_SHIFT)
#define RTC_RTC_IF_MIN_IF_VALUE_ENABLE 				1U
#define RTC_RTC_IF_MIN_IF_BITS_ENABLE  				(RTC_RTC_IF_MIN_IF_VALUE_ENABLE << RTC_RTC_IF_MIN_IF_SHIFT)

#define RTC_RTC_IF_HOUR_IF_SHIFT        				2
#define RTC_RTC_IF_HOUR_IF_WIDTH        				1
#define RTC_RTC_IF_HOUR_IF_MASK         				(((1U << RTC_RTC_IF_HOUR_IF_WIDTH) - 1U) << RTC_RTC_IF_HOUR_IF_SHIFT)
#define RTC_RTC_IF_HOUR_IF_VALUE_DISABLE				0U
#define RTC_RTC_IF_HOUR_IF_BITS_DISABLE 				(RTC_RTC_IF_HOUR_IF_VALUE_DISABLE << RTC_RTC_IF_HOUR_IF_SHIFT)
#define RTC_RTC_IF_HOUR_IF_VALUE_ENABLE 				1U
#define RTC_RTC_IF_HOUR_IF_BITS_ENABLE  				(RTC_RTC_IF_HOUR_IF_VALUE_ENABLE << RTC_RTC_IF_HOUR_IF_SHIFT)

#define RTC_RTC_IF_DATE_IF_SHIFT        				3
#define RTC_RTC_IF_DATE_IF_WIDTH        				1
#define RTC_RTC_IF_DATE_IF_MASK         				(((1U << RTC_RTC_IF_DATE_IF_WIDTH) - 1U) << RTC_RTC_IF_DATE_IF_SHIFT)
#define RTC_RTC_IF_DATE_IF_VALUE_DISABLE				0U
#define RTC_RTC_IF_DATE_IF_BITS_DISABLE 				(RTC_RTC_IF_DATE_IF_VALUE_DISABLE << RTC_RTC_IF_DATE_IF_SHIFT)
#define RTC_RTC_IF_DATE_IF_VALUE_ENABLE 				1U
#define RTC_RTC_IF_DATE_IF_BITS_ENABLE  				(RTC_RTC_IF_DATE_IF_VALUE_ENABLE << RTC_RTC_IF_DATE_IF_SHIFT)

#define RTC_RTC_IF_ALM_IF_SHIFT        				4
#define RTC_RTC_IF_ALM_IF_WIDTH        				1
#define RTC_RTC_IF_ALM_IF_MASK         				(((1U << RTC_RTC_IF_ALM_IF_WIDTH) - 1U) << RTC_RTC_IF_ALM_IF_SHIFT)
#define RTC_RTC_IF_ALM_IF_VALUE_DISABLE				0U
#define RTC_RTC_IF_ALM_IF_BITS_DISABLE 				(RTC_RTC_IF_ALM_IF_VALUE_DISABLE << RTC_RTC_IF_ALM_IF_SHIFT)
#define RTC_RTC_IF_ALM_IF_VALUE_ENABLE 				1U
#define RTC_RTC_IF_ALM_IF_BITS_ENABLE  				(RTC_RTC_IF_ALM_IF_VALUE_ENABLE << RTC_RTC_IF_ALM_IF_SHIFT)

#define RTC_RTC_IF_MS_IF_SHIFT        				5
#define RTC_RTC_IF_MS_IF_WIDTH        				1
#define RTC_RTC_IF_MS_IF_MASK         				(((1U << RTC_RTC_IF_MS_IF_WIDTH) - 1U) << RTC_RTC_IF_MS_IF_SHIFT)
#define RTC_RTC_IF_MS_IF_VALUE_DISABLE				0U
#define RTC_RTC_IF_MS_IF_BITS_DISABLE 				(RTC_RTC_IF_MS_IF_VALUE_DISABLE << RTC_RTC_IF_MS_IF_SHIFT)
#define RTC_RTC_IF_MS_IF_VALUE_ENABLE 				1U
#define RTC_RTC_IF_MS_IF_BITS_ENABLE  				(RTC_RTC_IF_MS_IF_VALUE_ENABLE << RTC_RTC_IF_MS_IF_SHIFT)

#define RTC_RTC_IF_TIME_ERR_SHIFT        				8
#define RTC_RTC_IF_TIME_ERR_WIDTH        				1
#define RTC_RTC_IF_TIME_ERR_MASK         				(((1U << RTC_RTC_IF_TIME_ERR_WIDTH) - 1U) << RTC_RTC_IF_TIME_ERR_SHIFT)
#define RTC_RTC_IF_TIME_ERR_VALUE_DISABLE				0U
#define RTC_RTC_IF_TIME_ERR_BITS_DISABLE 				(RTC_RTC_IF_TIME_ERR_VALUE_DISABLE << RTC_RTC_IF_TIME_ERR_SHIFT)
#define RTC_RTC_IF_TIME_ERR_VALUE_ENABLE 				1U
#define RTC_RTC_IF_TIME_ERR_BITS_ENABLE  				(RTC_RTC_IF_TIME_ERR_VALUE_ENABLE << RTC_RTC_IF_TIME_ERR_SHIFT)

#define RTC_RTC_IF_ALM_ERR_SHIFT        				9
#define RTC_RTC_IF_ALM_ERR_WIDTH        				1
#define RTC_RTC_IF_ALM_ERR_MASK         				(((1U << RTC_RTC_IF_ALM_ERR_WIDTH) - 1U) << RTC_RTC_IF_ALM_ERR_SHIFT)
#define RTC_RTC_IF_ALM_ERR_VALUE_DISABLE				0U
#define RTC_RTC_IF_ALM_ERR_BITS_DISABLE 				(RTC_RTC_IF_ALM_ERR_VALUE_DISABLE << RTC_RTC_IF_ALM_ERR_SHIFT)
#define RTC_RTC_IF_ALM_ERR_VALUE_ENABLE 				1U
#define RTC_RTC_IF_ALM_ERR_BITS_ENABLE  				(RTC_RTC_IF_ALM_ERR_VALUE_ENABLE << RTC_RTC_IF_ALM_ERR_SHIFT)

#define RTC_RTC_PRE_ADDR									(RTC_BASE_ADDR + 0x0010U)
#define RTC_RTC_PRE     									(*(volatile uint32_t *)RTC_RTC_PRE_ADDR)

#define RTC_RTC_PRE_PRE_ROUND_SHIFT        				0
#define RTC_RTC_PRE_PRE_ROUND_WIDTH        				20
#define RTC_RTC_PRE_PRE_ROUND_MASK         				(((1U << RTC_RTC_PRE_PRE_ROUND_WIDTH) - 1U) << RTC_RTC_PRE_PRE_ROUND_SHIFT)
#define RTC_RTC_PRE_PRE_ROUND_VALUE_DISABLE				0U
#define RTC_RTC_PRE_PRE_ROUND_BITS_DISABLE 				(RTC_RTC_PRE_PRE_ROUND_VALUE_DISABLE << RTC_RTC_PRE_PRE_ROUND_SHIFT)
#define RTC_RTC_PRE_PRE_ROUND_VALUE_ENABLE 				1U
#define RTC_RTC_PRE_PRE_ROUND_BITS_ENABLE  				(RTC_RTC_PRE_PRE_ROUND_VALUE_ENABLE << RTC_RTC_PRE_PRE_ROUND_SHIFT)

#define RTC_RTC_PRE_PRE_DECIMAL_SHIFT        				20
#define RTC_RTC_PRE_PRE_DECIMAL_WIDTH        				4
#define RTC_RTC_PRE_PRE_DECIMAL_MASK         				(((1U << RTC_RTC_PRE_PRE_DECIMAL_WIDTH) - 1U) << RTC_RTC_PRE_PRE_DECIMAL_SHIFT)
#define RTC_RTC_PRE_PRE_DECIMAL_VALUE_DISABLE				0U
#define RTC_RTC_PRE_PRE_DECIMAL_BITS_DISABLE 				(RTC_RTC_PRE_PRE_DECIMAL_VALUE_DISABLE << RTC_RTC_PRE_PRE_DECIMAL_SHIFT)
#define RTC_RTC_PRE_PRE_DECIMAL_VALUE_ENABLE 				1U
#define RTC_RTC_PRE_PRE_DECIMAL_BITS_ENABLE  				(RTC_RTC_PRE_PRE_DECIMAL_VALUE_ENABLE << RTC_RTC_PRE_PRE_DECIMAL_SHIFT)

#define RTC_RTC_PRE_PRE_PERIOD_SHIFT        				24
#define RTC_RTC_PRE_PRE_PERIOD_WIDTH        				1
#define RTC_RTC_PRE_PRE_PERIOD_MASK         				(((1U << RTC_RTC_PRE_PRE_PERIOD_WIDTH) - 1U) << RTC_RTC_PRE_PRE_PERIOD_SHIFT)
#define RTC_RTC_PRE_PRE_PERIOD_VALUE_8_SEC				    0U
#define RTC_RTC_PRE_PRE_PERIOD_BITS_8_SEC 				    (RTC_RTC_PRE_PRE_PERIOD_VALUE_8_SEC << RTC_RTC_PRE_PRE_PERIOD_SHIFT)
#define RTC_RTC_PRE_PRE_PERIOD_VALUE_16_SEC 				1U
#define RTC_RTC_PRE_PRE_PERIOD_BITS_16_SEC  				(RTC_RTC_PRE_PRE_PERIOD_VALUE_16_SEC << RTC_RTC_PRE_PRE_PERIOD_SHIFT)

#define RTC_RTC_TR_ADDR									(RTC_BASE_ADDR + 0x0014U)
#define RTC_RTC_TR     									(*(volatile uint32_t *)RTC_RTC_TR_ADDR)

#define RTC_RTC_TR_BCD_SEC_SHIFT        				0
#define RTC_RTC_TR_BCD_SEC_WIDTH        				4
#define RTC_RTC_TR_BCD_SEC_MASK         				(((1U << RTC_RTC_TR_BCD_SEC_WIDTH) - 1U) << RTC_RTC_TR_BCD_SEC_SHIFT)

#define RTC_RTC_TR_BCD_SEC_DEC_SHIFT        			4
#define RTC_RTC_TR_BCD_SEC_DEC_WIDTH        			3
#define RTC_RTC_TR_BCD_SEC_DEC_MASK         			(((1U << RTC_RTC_TR_BCD_SEC_DEC_WIDTH) - 1U) << RTC_RTC_TR_BCD_SEC_DEC_SHIFT)

#define RTC_RTC_TR_BCD_MIN_SHIFT        				8
#define RTC_RTC_TR_BCD_MIN_WIDTH        				4
#define RTC_RTC_TR_BCD_MIN_MASK         				(((1U << RTC_RTC_TR_BCD_MIN_WIDTH) - 1U) << RTC_RTC_TR_BCD_MIN_SHIFT)

#define RTC_RTC_TR_BCD_MIN_DEC_SHIFT        			12
#define RTC_RTC_TR_BCD_MIN_DEC_WIDTH        			3
#define RTC_RTC_TR_BCD_MIN_DEC_MASK         			(((1U << RTC_RTC_TR_BCD_MIN_DEC_WIDTH) - 1U) << RTC_RTC_TR_BCD_MIN_DEC_SHIFT)

#define RTC_RTC_TR_BCD_HOUR_SHIFT        				16
#define RTC_RTC_TR_BCD_HOUR_WIDTH        				4
#define RTC_RTC_TR_BCD_HOUR_MASK         				(((1U << RTC_RTC_TR_BCD_HOUR_WIDTH) - 1U) << RTC_RTC_TR_BCD_HOUR_SHIFT)

#define RTC_RTC_TR_BCD_HOUR_DEC_SHIFT        			20
#define RTC_RTC_TR_BCD_HOUR_DEC_WIDTH        			2
#define RTC_RTC_TR_BCD_HOUR_DEC_MASK         			(((1U << RTC_RTC_TR_BCD_HOUR_DEC_WIDTH) - 1U) << RTC_RTC_TR_BCD_HOUR_DEC_SHIFT)

#define RTC_RTC_TR_BCD_WEEK_SHIFT        				24
#define RTC_RTC_TR_BCD_WEEK_WIDTH        				3
#define RTC_RTC_TR_BCD_WEEK_MASK         				(((1U << RTC_RTC_TR_BCD_WEEK_WIDTH) - 1U) << RTC_RTC_TR_BCD_WEEK_SHIFT)

#define RTC_RTC_DR_ADDR									(RTC_BASE_ADDR + 0x0018U)
#define RTC_RTC_DR     									(*(volatile uint32_t *)RTC_RTC_DR_ADDR)

#define RTC_RTC_DR_BCD_DATE_SHIFT        				0
#define RTC_RTC_DR_BCD_DATE_WIDTH        				4
#define RTC_RTC_DR_BCD_DATE_MASK         				(((1U << RTC_RTC_DR_BCD_DATE_WIDTH) - 1U) << RTC_RTC_DR_BCD_DATE_SHIFT)

#define RTC_RTC_DR_BCD_DATE_DEC_SHIFT        			4
#define RTC_RTC_DR_BCD_DATE_DEC_WIDTH        			2
#define RTC_RTC_DR_BCD_DATE_DEC_MASK         			(((1U << RTC_RTC_DR_BCD_DATE_DEC_WIDTH) - 1U) << RTC_RTC_DR_BCD_DATE_DEC_SHIFT)

#define RTC_RTC_DR_BCD_MONTH_SHIFT        				8
#define RTC_RTC_DR_BCD_MONTH_WIDTH        				4
#define RTC_RTC_DR_BCD_MONTH_MASK         				(((1U << RTC_RTC_DR_BCD_MONTH_WIDTH) - 1U) << RTC_RTC_DR_BCD_MONTH_SHIFT)

#define RTC_RTC_DR_BCD_MONTH_DEC_SHIFT        			12
#define RTC_RTC_DR_BCD_MONTH_DEC_WIDTH        			1
#define RTC_RTC_DR_BCD_MONTH_DEC_MASK         			(((1U << RTC_RTC_DR_BCD_MONTH_DEC_WIDTH) - 1U) << RTC_RTC_DR_BCD_MONTH_DEC_SHIFT)

#define RTC_RTC_DR_BCD_YEAR_SHIFT        				16
#define RTC_RTC_DR_BCD_YEAR_WIDTH        				4
#define RTC_RTC_DR_BCD_YEAR_MASK         				(((1U << RTC_RTC_DR_BCD_YEAR_WIDTH) - 1U) << RTC_RTC_DR_BCD_YEAR_SHIFT)

#define RTC_RTC_DR_BCD_YEAR_DEC_SHIFT        			20
#define RTC_RTC_DR_BCD_YEAR_DEC_WIDTH        			3
#define RTC_RTC_DR_BCD_YEAR_DEC_MASK         			(((1U << RTC_RTC_DR_BCD_YEAR_DEC_WIDTH) - 1U) << RTC_RTC_DR_BCD_YEAR_DEC_SHIFT)

#define RTC_RTC_AR_ADDR									(RTC_BASE_ADDR + 0x001CU)
#define RTC_RTC_AR     									(*(volatile uint32_t *)RTC_RTC_AR_ADDR)

#define RTC_RTC_AR_ALM_SEC_SHIFT        				0
#define RTC_RTC_AR_ALM_SEC_WIDTH        				4
#define RTC_RTC_AR_ALM_SEC_MASK         				(((1U << RTC_RTC_AR_ALM_SEC_WIDTH) - 1U) << RTC_RTC_AR_ALM_SEC_SHIFT)

#define RTC_RTC_AR_ALM_SEC_DEC_SHIFT        			4
#define RTC_RTC_AR_ALM_SEC_DEC_WIDTH        			3
#define RTC_RTC_AR_ALM_SEC_DEC_MASK         			(((1U << RTC_RTC_AR_ALM_SEC_DEC_WIDTH) - 1U) << RTC_RTC_AR_ALM_SEC_DEC_SHIFT)

#define RTC_RTC_AR_ALM_MIN_SHIFT        				8
#define RTC_RTC_AR_ALM_MIN_WIDTH        				4
#define RTC_RTC_AR_ALM_MIN_MASK         				(((1U << RTC_RTC_AR_ALM_MIN_WIDTH) - 1U) << RTC_RTC_AR_ALM_MIN_SHIFT)

#define RTC_RTC_AR_ALM_MIN_DEC_SHIFT        			12
#define RTC_RTC_AR_ALM_MIN_DEC_WIDTH        			3
#define RTC_RTC_AR_ALM_MIN_DEC_MASK         			(((1U << RTC_RTC_AR_ALM_MIN_DEC_WIDTH) - 1U) << RTC_RTC_AR_ALM_MIN_DEC_SHIFT)

#define RTC_RTC_AR_ALM_HOUR_SHIFT        				16
#define RTC_RTC_AR_ALM_HOUR_WIDTH        				4
#define RTC_RTC_AR_ALM_HOUR_MASK         				(((1U << RTC_RTC_AR_ALM_HOUR_WIDTH) - 1U) << RTC_RTC_AR_ALM_HOUR_SHIFT)

#define RTC_RTC_AR_ALM_HOUR_DEC_SHIFT        			20
#define RTC_RTC_AR_ALM_HOUR_DEC_WIDTH        			1
#define RTC_RTC_AR_ALM_HOUR_DEC_MASK         			(((1U << RTC_RTC_AR_ALM_HOUR_DEC_WIDTH) - 1U) << RTC_RTC_AR_ALM_HOUR_DEC_SHIFT)

#define RTC_RTC_AR_ALM_WEEK_SHIFT        				24
#define RTC_RTC_AR_ALM_WEEK_WIDTH        				3
#define RTC_RTC_AR_ALM_WEEK_MASK         				(((1U << RTC_RTC_AR_ALM_WEEK_WIDTH) - 1U) << RTC_RTC_AR_ALM_WEEK_SHIFT)

#define RTC_RTC_TSTR_ADDR							(RTC_BASE_ADDR + 0x0020U)
#define RTC_RTC_TSTR     							(*(volatile uint32_t *)RTC_RTC_TSTR_ADDR)

#define RTC_RTC_TSTR_SEC_SHIFT        				0
#define RTC_RTC_TSTR_SEC_WIDTH        				4
#define RTC_RTC_TSTR_SEC_MASK         				(((1U << RTC_RTC_TSTR_SEC_WIDTH) - 1U) << RTC_RTC_TSTR_SEC_SHIFT)

#define RTC_RTC_TSTR_SEC_DEC_SHIFT        			4
#define RTC_RTC_TSTR_SEC_DEC_WIDTH        			3
#define RTC_RTC_TSTR_SEC_DEC_MASK         			(((1U << RTC_RTC_TSTR_SEC_DEC_WIDTH) - 1U) << RTC_RTC_TSTR_SEC_DEC_SHIFT)

#define RTC_RTC_TSTR_MIN_SHIFT        				8
#define RTC_RTC_TSTR_MIN_WIDTH        				4
#define RTC_RTC_TSTR_MIN_MASK         				(((1U << RTC_RTC_TSTR_MIN_WIDTH) - 1U) << RTC_RTC_TSTR_MIN_SHIFT)

#define RTC_RTC_TSTR_MIN_DEC_SHIFT        			12
#define RTC_RTC_TSTR_MIN_DEC_WIDTH        			3
#define RTC_RTC_TSTR_MIN_DEC_MASK         			(((1U << RTC_RTC_TSTR_MIN_DEC_WIDTH) - 1U) << RTC_RTC_TSTR_MIN_DEC_SHIFT)

#define RTC_RTC_TSTR_HOUR_SHIFT        				16
#define RTC_RTC_TSTR_HOUR_WIDTH        				4
#define RTC_RTC_TSTR_HOUR_MASK         				(((1U << RTC_RTC_TSTR_HOUR_WIDTH) - 1U) << RTC_RTC_TSTR_HOUR_SHIFT)

#define RTC_RTC_TSTR_HOUR_DEC_SHIFT        			20
#define RTC_RTC_TSTR_HOUR_DEC_WIDTH        			2
#define RTC_RTC_TSTR_HOUR_DEC_MASK         			(((1U << RTC_RTC_TSTR_HOUR_DEC_WIDTH) - 1U) << RTC_RTC_TSTR_HOUR_DEC_SHIFT)

#define RTC_RTC_TSTR_WEEK_SHIFT        				24
#define RTC_RTC_TSTR_WEEK_WIDTH        				3
#define RTC_RTC_TSTR_WEEK_MASK         				(((1U << RTC_RTC_TSTR_WEEK_WIDTH) - 1U) << RTC_RTC_TSTR_WEEK_SHIFT)

#define RTC_RTC_TSDR_ADDR							(RTC_BASE_ADDR + 0x0024U)
#define RTC_RTC_TSDR     							(*(volatile uint32_t *)RTC_RTC_TSDR_ADDR)

#define RTC_RTC_TSDR_DATE_SHIFT        				0
#define RTC_RTC_TSDR_DATE_WIDTH        				4
#define RTC_RTC_TSDR_DATE_MASK         				(((1U << RTC_RTC_TSDR_DATE_WIDTH) - 1U) << RTC_RTC_TSDR_DATE_SHIFT)

#define RTC_RTC_TSDR_DATE_DEC_SHIFT        			4
#define RTC_RTC_TSDR_DATE_DEC_WIDTH        			2
#define RTC_RTC_TSDR_DATE_DEC_MASK         			(((1U << RTC_RTC_TSDR_DATE_DEC_WIDTH) - 1U) << RTC_RTC_TSDR_DATE_DEC_SHIFT)

#define RTC_RTC_TSDR_MONTH_SHIFT        			8
#define RTC_RTC_TSDR_MONTH_WIDTH        			4
#define RTC_RTC_TSDR_MONTH_MASK         			(((1U << RTC_RTC_TSDR_MONTH_WIDTH) - 1U) << RTC_RTC_TSDR_MONTH_SHIFT)

#define RTC_RTC_TSDR_MONTH_DEC_SHIFT        		12
#define RTC_RTC_TSDR_MONTH_DEC_WIDTH        		1
#define RTC_RTC_TSDR_MONTH_DEC_MASK         		(((1U << RTC_RTC_TSDR_MONTH_DEC_WIDTH) - 1U) << RTC_RTC_TSDR_MONTH_DEC_SHIFT)

#define RTC_RTC_TSDR_YEAR_SHIFT        				16
#define RTC_RTC_TSDR_YEAR_WIDTH        				4
#define RTC_RTC_TSDR_YEAR_MASK         				(((1U << RTC_RTC_TSDR_YEAR_WIDTH) - 1U) << RTC_RTC_TSDR_YEAR_SHIFT)

#define RTC_RTC_TSDR_YEAR_DEC_SHIFT        			20
#define RTC_RTC_TSDR_YEAR_DEC_WIDTH        			3
#define RTC_RTC_TSDR_YEAR_DEC_MASK         			(((1U << RTC_RTC_TSDR_YEAR_DEC_WIDTH) - 1U) << RTC_RTC_TSDR_YEAR_DEC_SHIFT)

#endif